#ifndef NETWORKTOOLSLIB_GLOBAL_H
#define NETWORKTOOLSLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NETWORKTOOLSLIB_LIBRARY)
#  define NETWORKTOOLSLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NETWORKTOOLSLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NETWORKTOOLSLIB_GLOBAL_H
